### ISSUE TITLE
Refactor infrastructure

### ISSUE THREAD

**Issue by NikitaShkaruba** [gravity-ui/websql-autocomplete#84]
Subtasks:
- [x] https://github.com/gravity-ui/sql-autocomplete-parsers/issues/23
- [x] https://github.com/gravity-ui/sql-autocomplete-parsers/issues/24
- [x] https://github.com/gravity-ui/sql-autocomplete-parsers/issues/55
- [x] #85
- [x] #86
- [x] #87
